services:
  postgres:
    image: postgres:17
    container_name: otp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: otp
    ports:
      - 5432:5432